### ISSUE TITLE
Is there a way to get the new blob directly after stripping the image without rewrite image?

### ISSUE THREAD

**Issue by ohno104** [nlfiedler/magick-rust#116]
Is there a way to get the new blob directly after stripping the image without rewrite image?
I try to get new blob directly after `strip_image()`, It's seen to need to `write_image()` first.
Is there any way to do this or am I missing something?

![image](https://github.com/nlfiedler/magick-rust/assets/78719026/6cbf69ad-b8cb-4e92-828f-48c83b8bc73c)

**Comment by nlfiedler** [comment]
I haven't kept up with all of the contributions to the project so I'm not as familiar with it as I used to be, but I do believe that it is necessary to write the image. For the most part, this crate is a direct translation from the ImageMagick library, so if there is a suitable function there that is missing here, let me know and we can get that added.

**Comment by ohno104** [comment]
got that, thank you for your help.
