### ISSUE TITLE
Getting to a 1.0 release

### ISSUE THREAD

**Issue by nlfiedler** [nlfiedler/magick-rust#122]
This library is several years old, maybe now is as good a time as any to prepare for a 1.0 release. After that, any breaking changes means bumping the major version, and that seems a better approach for the long run. As it is now, a minor bump at pre-1.0 looks deceptively minor when in fact it may not be minor at all.

@5ohue Thoughts? My role on this repository is primarily that of curator, and given your many recent significant contributions of late, you are as qualified as any to decide the appropriate time for the next release. Do you have more changes planned, or is now a good time to ship 1.0?

And thank you again for your many contributions.

**Comment by 5ohue** [comment]
For now as I'm kind of wrapping up what I'm working on.

I have only a small contribution that I am planning to do which is making the wand types `Send`. Maybe one or two more things will be added as I'm wrapping up.

I would say, you can start the 1.0 version in a week, by then I'll have no more commits to contribute for a while.
