### ISSUE TITLE
Version of ImageMagick  should be >= v7.1.1.26 for the latest magick-rust

### ISSUE THREAD

**Issue by turtlemeow** [nlfiedler/magick-rust#125]
The version of imagemagick should be later than 7.1.1.26 because `OffIfOpaque` AlphaChannelOption is available after this version. Otherwise may cause compile failures.

https://github.com/nlfiedler/magick-rust/blob/master/src/types/alpha_channel_option.rs#L37

**Comment by nlfiedler** [comment]
For now, the best I can do is update the `build.rs` to require 7.1.1 (adding -26 or .26 doesn't work) and update the README file. Thanks for letting me know. Fixed in commit d50f01b
