### ISSUE TITLE
Build error: `you should set MAGICKCORE_HDRI_ENABLE` (Debian Experimental)

### ISSUE THREAD

**Issue by Des-Nerger** [nlfiedler/magick-rust#131]
[magick_rust_build_error_MAGICKCORE_HDRI_ENABLE.log](https://github.com/user-attachments/files/16724449/magick_rust_build_error_MAGICKCORE_HDRI_ENABLE.log)

**Comment by nlfiedler** [comment]
For this particular platform, you may need to add `default-features = false` to the `magick-rust` dependency. The crate is building fine on macOS and the docker image, so it seems specific to this platform.

**Comment by Des-Nerger** [comment]
I tried `magick_rust = { version = "1.0.0", default-features = false }`, but unfortunately it doesn't seem to have any effect: the build log and error gotten are exactly the same.

**Comment by nlfiedler** [comment]
I'd like to debug this further. What Debian release are you using, and version of ImageMagick? Any other details that might make a difference?

**Comment by Des-Nerger** [comment]
The problem was caused by [the Debian package](https://salsa.debian.org/debian/imagemagick/-/tree/debian/lastest/debian) not supplying the `MagickCore-config` script. I added a workaround. But now I get another error: [magick_rust_u16_from_f32_not_satisfied.log](https://github.com/user-attachments/files/16743566/magick_rust_u16_from_f32_not_satisfied.log)
