### ISSUE TITLE
version problems

### ISSUE THREAD

**Issue by MarkSwanson** [nlfiedler/magick-rust#20]
$ RUST_BACKTRACE=1 cargo build
   Compiling magick_rust v0.6.1 (file:///home/zz/src/external/magick-rust)
error: failed to run custom build command for `magick_rust v0.6.1 (file:///home/zz/src/external/magick-rust)`
process didn't exit successfully: `/home/zz/src/external/magick-rust/target/debug/build/magick_rust-79a7ed904c8f6b4d/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:783
stack backtrace:
  11:     0x55c980e2d36b - build_script_build::assert_mw_version::h77cf9f50013c43d3
                        at /home/sc/src/external/magick-rust/build.rs:125

System: Ubuntu 14

Solution:

sudo apt-get install pkg-config

Maybe add that to the list of dependencies that must be installed?

Thanks for all of your effort with magick-rust!

**Comment by nlfiedler** [comment]
Excellent point, I had forgotten that it is not always present by default. Fixed in commit 2eccf1e91ba2403679fc33f59c4e92163318cdae.
