### ISSUE TITLE
cargo build failed

### ISSUE THREAD

**Issue by Mignet** [nlfiedler/magick-rust#4]
hi, when I run `cargo build --verbose`,get some errors like below:
------------------------------------------------------
[root@localhost magick-rust]# cargo build --verbose
   Compiling libc v0.2.10
     Running `rustc /root/.cargo/registry/src/github.com-88ac128001ac3a9a/libc-0.2.10/src/lib.rs --crate-name libc --crate-type lib -g --cfg feature=\"default\" --cfg feature=\"use_std\" -C metadata=12d5d911cf5411c3 -C extra-filename=-12d5d911cf5411c3 --out-dir /root/projects/magick-rust/target/debug/deps --emit=dep-info,link -L dependency=/root/projects/magick-rust/target/debug/deps -L dependency=/root/projects/magick-rust/target/debug/deps --cap-lints allow`
   Compiling magick_rust v0.4.0 (file:///root/projects/magick-rust)
     Running `rustc build.rs --crate-name build_script_build --crate-type bin -g --out-dir /root/projects/magick-rust/target/debug/build/magick_rust-69f577ee4bd14cfc --emit=dep-info,link -L dependency=/root/projects/magick-rust/target/debug -L dependency=/root/projects/magick-rust/target/debug/deps`
     Running `/root/projects/magick-rust/target/debug/build/magick_rust-69f577ee4bd14cfc/build-script-build`
Build failed, waiting for other jobs to finish...
failed to run custom build command for `magick_rust v0.4.0 (file:///root/projects/magick-rust)`
Process didn't exit successfully: `/root/projects/magick-rust/target/debug/build/magick_rust-69f577ee4bd14cfc/build-script-build` (exit code: 101)
--- stdout
/usr/bin/MagickWand-config

--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:688

**Comment by nlfiedler** [comment]
That is a mysterious failure indeed. Unfortunately they are always like that with the build.rs mechanism. The only error handling is what is written in build.rs, so I have everything that I know about, but nothing more. Your best bet is to add some println!() calls throughout build.rs and look at the target/debug/build/magick_rust-*/output file for the output.

**Comment by nlfiedler** [comment]
The build script has been improved significantly, so it is possible this issue has been resolved as a result. If it reappears, please feel free to reopen this issue, or create a new one, as appropriate.
