### ISSUE TITLE
How to compile for x86_64-unknown-linux-musl target

### ISSUE THREAD

**Issue by davidarmstronglewis** [nlfiedler/magick-rust#53]
Hi there! Thanks for maintaining this crate!

How would I go about building a crate that depends on this one for the x86_64-unknown-linux-musl target? Is that something that is supported currently?

**Comment by nlfiedler** [comment]
That's a great question, unfortunately I have no idea. I suspect it depends a lot on how well the rust-bindgen tool supports that particular target.

**Comment by davidarmstronglewis** [comment]
Yeah, sadly I currently don't know enough about the process to modify `build.rs` to account for that target.
