### ISSUE TITLE
*Wand is `Send` or `!Send`

### ISSUE THREAD

**Issue by DCjanus** [nlfiedler/magick-rust#74]
In Rust lang, each type is marked `Send` or `!Send`, in `magick-rust`, I noticed that `DrawingWand`, `MagickWand` And `PixedWand` is `!Send`, is that correct?

**Comment by nlfiedler** [comment]
Not sure, I am merely the happy recipient of those code changes that someone else made. I would guess that it has something to do with the connection to resources outside of the control of Rust, i.e. the memory managed by ImageMagick itself.
