### ISSUE TITLE
Fails on ImageMagick 7

### ISSUE THREAD

**Issue by hjr3** [nlfiedler/magick-rust#8]
The new release of ImageMagick 7 changes the structure of the header files. The `gen.h` file that is created using `build.rs` does not reflect that new structure. The build will fail because `#include <wand/MagickWand.h>` is no longer correct.

Also, https://github.com/nlfiedler/magick-rust/blob/master/vagrant/ubuntu14/fabfile.py currently downloads the latest stable build. This transparently switched from ImageMagick 6.9 to ImageMagick 7. We may want to consider being more explicit with the version.

**Comment by nlfiedler** [comment]
Yes, I noticed this as well. I'll try to address this in a week.

**Comment by nlfiedler** [comment]
Can use `pkg-config --max-version=7.0 MagickWand` to determine whether the ImageMagick library is the newer version or not: `pkg-config` will exit 0 if MagickWand is less than 7.0, and 1 otherwise. The `build.rs` can then adjust the output of the `gen.h` to suit the MagickWand header file layout.

**Comment by nlfiedler** [comment]
Using 7.0 is going to be a more significant change than I want to take on right now. I've adjusted the `fabfile.py` for the Ubuntu VM to grab the recent 6.9 tarball. Upgrading to 7.0 is going to require not only changing the `build.rs` script, but also removing two functions that had previously been deprecated and subsequently removed, as well as several functions whose arguments have changed. For now, we must avoid 7.0. See issue #11 for the upgrade plan.

**Comment by hjr3** [comment]
No problem here. I am using 6.9 at the moment.
