### ISSUE TITLE
MagickWand version validation issue

### ISSUE THREAD

**Issue by dansandland** [nlfiedler/magick-rust#83]
I have ImageMagick `7.1.0-4` installed and get the message `MagickWand version must be no higher than 7.1` when building the library.

```
❯ magick --version
Version: ImageMagick 7.1.0-4 Q16 x86_64 2021-07-18 https://imagemagick.org
```
```
❯ cargo build
...
  --- stderr
  thread 'main' panicked at 'MagickWand version must be no higher than 7.1', /Users/dansandland/.cargo/registry/src/github.com-1ecc6299db9ec823/magick_rust-0.14.0/build.rs:252:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by nlfiedler** [comment]
Which commit/branch are you building from? The latest code should be building again 7.1 without issue.

**Comment by Jacherr** [comment]
This also happens to me when building from the latest commit or building from the latest release (0.14.0).

**Comment by DCjanus** [comment]
same issue with me.

crate: magick_rust = `0.14.0`
pkg-config version 1.7.3
platform: ArchLinux 64bit

**Comment by DCjanus** [comment]
Maybe we should run command like this to check version: `pkg-config --print-errors --exists 'MagickWand < 7.2 MagickWand >= 7.0.0'`, since it looks like that `7.1.0-4` greater than `7.1`

**Comment by nlfiedler** [comment]
I'm sorry, I had assumed that we were talking about the latest commit. Yes, the release from last year does not have the updated version check. I will put out a release shortly.

**Comment by nlfiedler** [comment]
Just pushed 0.15 to crates.io, that should resolve the version check. Sorry for not publishing sooner, hard to believe it's already been a year since the last release. If anyone is in need of a new release, please file an issue. Thanks.
