### ISSUE TITLE
Add to crates.io

### ISSUE THREAD

**Issue by hjr3** [nlfiedler/magick-rust#9]
Is there any plan to add this crates.io? I would rather not pin a specific commit so we can get upstream patches in the future.

**Comment by nlfiedler** [comment]
There were no plans in place, but I agree that it is worth considering now that there are many more functions exposed through the wrapper. Previously it was rather anemic, and hardly worth publishing. I have two weeks off from work coming up, I'll look into it then.

**Comment by hjr3** [comment]
I am happy to help in any way I can ;)

**Comment by nlfiedler** [comment]
Done: https://crates.io/crates/magick_rust

**Comment by hjr3** [comment]
Awesome, thank you for this.
